default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ENV['DATABASE_USERNAME']
  password: ENV['DATABASE_PASSWORD']
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ENV['DATABASE_DEVELOPMENT']
  

test:
  <<: *default
  database: ENV['DATABASE_TEST']

production:
  <<: *default
  database: exchange_rate_prod